import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'story_list_item_model.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'story_list_item_model.g.dart';

/// Model for Story List
@freezed
class StoryListItemModel with _$StoryListItemModel {
  const factory StoryListItemModel({
    required int userId,
    required String profileImage,
    required String name,
  }) = _StoryListItemModel;

  factory StoryListItemModel.fromJson(Map<String, Object?> json) =>
      _$StoryListItemModelFromJson(json);
}